### ISSUE TITLE
How can I add a field current_time

### ISSUE THREAD

**Issue by phaothu** [repeatedly/fluent-plugin-record-modifier#10]
Is there some thinks like current_time $(time) ?

**Comment by repeatedly** [comment]
You can use any ruby code inside `${xxx}`: https://github.com/repeatedly/fluent-plugin-record-modifier#configuration

You can get current time using Ruby.

**Comment by phaothu** [comment]
With host_name $(hostname)  it work ok 

but when I change to current_time ${Time.now.to_s} it just show exactly the same "current_time" "${Time.now.to_s}"

**Comment by repeatedly** [comment]
> but when I change to current_time ${Time.now.to_s} it just show exactly the same "current_time":"${Time.now.to_s}"

Which version do you use?
Filter version supports ruby code but Output version doesn't.

**Comment by phaothu** [comment]
I am using 

td-agent-2.1.2-0.x86_64

ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]

And use command : /opt/td-agent/embedded/bin/fluent-gem install fluent-plugin-record-modifier to install this plugin

**Comment by repeatedly** [comment]
Please paste your configuration together.

**Comment by phaothu** [comment]
Below are my config , I want to add a filed current_time before push into hdfs 
<match test>
    type record_modifier
    current_time ${Time.now.to_s}
    tag test.finished
</match>

<match test.finished>
 type webhdfs
 host localhost
 port 50070
 path /test/%Y%m%d_%H
 username hdfs
 output_include_tag false
 buffer_type file
 buffer_path /mnt/ramdisk/test
 buffer_chunk_limit 4m
 buffer_queue_limit 50
 flush_interval 5s
</match>

**Comment by repeatedly** [comment]
```
<match test>
    type record_modifier
    current_time ${Time.now.to_s}
    tag test.finished
</match>
```

This is the cause. Use filter version instead of output.

**Comment by phaothu** [comment]
It worked !! Thank you so much
