### ISSUE TITLE
BUG: use router.emit_stream instead of Engine.emit_stream with Fluentd 0.14.4

### ISSUE THREAD

**Issue by StevenACoffman** [repeatedly/fluent-plugin-record-modifier#18]
It appears that fluent 0.14.4 wants plugins to update, specifically in fluent-plugin-record-modifier-0.5.0/lib/fluent/plugin/out_record_modifier.rb:79 to use router.emit_stream instead of Engine.emit_stream

The relevant line in [fluentd is here](https://github.com/fluent/fluentd/blob/master/lib/fluent/engine.rb#L169)
The relevant line in [out_record_modifier.rb is here](https://github.com/repeatedly/fluent-plugin-record-modifier/blob/master/lib/fluent/plugin/out_record_modifier.rb#L79)

I created a gist to [reproduce the error here](https://gist.github.com/StevenACoffman/b43e0c515c351a5c281980564e4ef294). 

+ I am running latest Docker (17.03.1-ce-mac5 (16048)) on Mac OS X El Capitan 10.11.6 (15G1421).
+ I am pulling the latest fluentd (0.14.4) using the latest fluent docker image (fluent/fluentd:v0.14).
+ I am using fluent-plugin-flowcounter v0.4.2

**Comment by repeatedly** [comment]
out_record_modifier is mainly for v0.10.
I can fix it but I have a plan to remove out_record_modifier in the future.
So I recommend to use output version on production.
And for chaning tag, router or retag plugin is better.

**Comment by StevenACoffman** [comment]
Fair enough. 
Is this plugin fully deprecated in favor of:

+ [filter_record_transformer](http://docs.fluentd.org/v0.14/articles/filter_record_transformer)
+ [fluent-plugin-route](https://github.com/tagomoris/fluent-plugin-route)
+ [fluent-plugin-retag](https://github.com/algas/fluent-plugin-retag)

Or are there still use cases?

**Comment by repeatedly** [comment]
record_modifier is faster than record_transformer. See README.
Some users hit performance issue with record_transforer on high workload.
This plugin is useful for such cases.

> I noticed that fluent-plugin-rewrite-tag-filter specifies the supported Fluentd version explicitly to exclude fluent versions 0.14 and higher so I assume that's also not a good option.

See https://github.com/fluent/fluent-plugin-rewrite-tag-filter/pull/30

**Comment by StevenACoffman** [comment]
Thank you. So you are still planning on updating this plugin to fluent v0.14.  Is Pull request #14  under active review?

**Comment by jcerjak** [comment]
How can the [capture fluentd logs](http://docs.fluentd.org/v0.14/articles/logging#capture-fluentd-logs) example be rewritten without using `out_record_modifier`? We plan to use something like this to send Fluentd errors to Sentry:

```
<match fluent.**>
  @type record_modifier
  tag message.fluent
  include_tag_key
  tag_key original_tag
</match>
<match message.fluent>
  @type grep
  regexp1 original_tag fluent.(warn|error|fatal)
  tag exception.fluent
</match>
<match exception.fluent>
  @type sentry
  endpoint_url <SENTRY_DSN>
  hostname_command hostname -s
</match>
```

**Comment by repeatedly** [comment]
Release v1.0.0.rc1 for v0.14 and release v0.6.0 for v0.12 with `router.emit` version.

**Comment by repeatedly** [comment]
@jcerjak If you want to send fluentd logs to sentry directly, tag rewrite is not needed.
Here is an example (not tested):

```
<filter fluent.**>
  @type record_transformer
  <record>
    original_tag ${tag}
  </record>
</match>
<filter fluent.**>
  @type grep
  regexp1 original_tag fluent.(warn|error|fatal)
</match>
<match fluent.**>
  @type sentry
  endpoint_url <SENTRY_DSN>
  hostname_command hostname -s
</match>
```

**Comment by jcerjak** [comment]
Thank you very much @repeatedly, I can confirm that this works with Fluentd v0.12, just had to fix the end tag for filters (`</filter>` instead of `</match>`):

```
<filter fluent.**>
  @type record_transformer
  <record>
    original_tag ${tag}
  </record>
</filter>
<filter fluent.**>
  @type grep
  regexp1 original_tag fluent.(warn|error|fatal)
</filter>
<match fluent.**>
  @type sentry
  endpoint_url <SENTRY_DSN>
  hostname_command hostname -s
</match>
```
