### ISSUE TITLE
Inaccuracies in README.md

### ISSUE THREAD

**Issue by shaburov** [repeatedly/fluent-plugin-record-modifier#23]
For install fluent-plugin-record-modifier needed ruby-**dev** for native extantions
Error:
```
sudo gem install fluent-plugin-record-modifierFetching: msgpack-1.1.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-record-modifier:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.4.0/gems/msgpack-1.1.0/ext/msgpack
/usr/bin/ruby2.4 -r ./siteconf20170930-10713-yrm82a.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.4.0/gems/msgpack-1.1.0 for inspection.
Results logged to /var/lib/gems/2.4.0/extensions/x86_64-linux/2.4.0/msgpack-1.1.0/gem_make.out
```

Add information about installing ruby
```
$ sudo apt-add-repository ppa:brightbox/ruby-ng
$ sudo apt-get update
Install the packages you need:
$ sudo apt-get install ruby2.4 ruby2.4-dev
```

**Comment by repeatedly** [comment]
No, fluent-plugin-record-modifier itself doesn't need ruby-dev.
I assume you didn't install fluentd itself.

**Comment by shaburov** [comment]
![image](https://user-images.githubusercontent.com/15269131/31045236-bd89e908-a5e7-11e7-9e91-a75d6740eeaa.png)
td-agent was installed 2 months ago

And now I have one more error
![image](https://user-images.githubusercontent.com/15269131/31045248-0f2268ee-a5e8-11e7-910f-df080745263b.png)
![image](https://user-images.githubusercontent.com/15269131/31045263-54c12dea-a5e8-11e7-9c14-94d13031f8c1.png)
`2017-09-30 13:57:08 +0300 [error]: dry run failed: Unknown filter plugin 'record-modifier'. Run 'gem search -rd fluent-plugin' to find plugins`

**Comment by shaburov** [comment]
For td-agent version 2+
`td-agent-gem install fluent-plugin-record-modifier`

**Comment by repeatedly** [comment]
It is FAQ. See official document: https://docs.fluentd.org/v0.12/articles/faq#i-installed-td-agent-and-want-to-add-custom-plugins-how-do-i-do-it
