### ISSUE TITLE
New fields added must be added to whitelist_keys (if it's used)

### ISSUE THREAD

**Issue by dannyk81** [repeatedly/fluent-plugin-record-modifier#24]
First, thanks for this plugin! :)

We've noticed that if `whitelist_keys` is used and new fields are added using `<record>...</record>`, these fields must also be added to `whitelist_keys` or we don't see them in emitted events, in a sense it make sense but would be nice if these fields would ne whitelisted by default.

Example:
```
<filter trans>
  @type record_modifier
  <record>
    project <something-here>
    docker_env <something-there>
  </record>
  whitelist_keys HOSTNAME,MESSAGE,CONTAINER_NAME,project,docker_env
</filter>
```

In the above example, if we don't include `project` and `docker_env` in whitelist_keys we don't get them.

**Comment by dannyk81** [comment]
ping @repeatedly :wink:

**Comment by repeatedly** [comment]
Your proposal seems reasonable. I will add it.
