### ISSUE TITLE
Unable to create nested key

### ISSUE THREAD

**Issue by thefirstofthe300** [repeatedly/fluent-plugin-record-modifier#39]
I am attempting to parse a Tomcat access log. I am currently using a regex parser to do so. The parser works well and all the expected fields are created.

From there, I'd like to be able to take some of the the records created by the regex parser and structure them in key-dictionary pair,. For example, I'd like
```
record {
  httpVersion:  "HTTP/1.1"   
  remoteIp:  "10.0.23.251"   
  requestMethod:  "GET"   
  responseSize:  "2"   
  status:  "200"   
  textPayload:  "/app/api/1.1/healthcheck/status"   
  timestamp:  "30/Nov/2018:19:01:01 -0600"   
 }
```
to become 
```
record {
  httpRequest: {
    remoteIp:  "10.0.23.251"
    httpVersion:  "HTTP/1.1"
    requestMethod:  "GET"
    responseSize:  "2"
    status:  "200"
  }
  textPayload:  "/forms/api/1.1/healthcheck/status"
  timestamp:  "30/Nov/2018:19:01:01 -0600"
}
```

I have tried using
```
<filter **.localhost-access-log>
  @type record_transformer
  <record>
    ${record["httpRequest"]["remoteIp"]} ${record["remoteIp"]}
  </record>
</filter>
```
```
<filter **.localhost-access-log>
  @type record_transformer
  <record>
    httpRequest.remoteIp ${record["remoteIp"]}
  </record>
</filter>
```
and even
```
<filter **.localhost-access-log>
  @type record_transformer
  <record>
    $.httpRequest.remoteIp ${record["remoteIp"]}
  </record>
</filter>
```
So far nothing has worked.

Does record transformation even support doing this?

I would try to take another approach to the problem but I have no control over the server that I'm importing this the logs into and changing the log format in Tomcat isn't very practical as it would require changes to many different applications owned by different teams.

**Comment by repeatedly** [comment]
> record_transformer

This repository is for `record_modifier`, not `record_transofmer`.
So your quesiton is not right place.

> I have no control over the server that I'm importing this the logs into

Does this mean you can't put your parser on forwarder side?
Best approach is using own parser, wrap regexp parser to create nested field, for this case.

**Comment by thefirstofthe300** [comment]
Thanks for the help. You are right, this issue is in the wrong repo :man_facepalming:.

> Does this mean you can't put your parser on forwarder side?

Essentially what this means is that the shape of the exported record is not something I can change. In order to get the aggregation server (in this case Stackdriver) to parse the logs in a favorable way, I have to match their defined ingestion format.

That being said, I did figure out a solution to my issue. The following filter block did the trick:

```
<filter **.localhost-access-log>
  @type record_transformer
  enable_ruby true
  auto_typecast true
  remove_keys _dummy_,remoteIp,requestMethod,requestUrl,responseSize,status
  <record>
   httpRequest ${{"remoteIp": record['remoteIp'], "requestMethod": record['requestMethod'], "requestUrl": record['requestUrl'], "responseSize": record['responseSize'], "status": record['status']}}
   severity ${record['status'].to_i < 400 ? record['severity'] = 'INFO' : record['severity'] = 'WARNING';}
  </record>
</filter>
```

**Comment by kush003** [comment]
Hello @thefirstofthe300 

I am also trying like same thing.

I have data like:
**"log_processed": {
    "orgId": 33274,
    "responseCode": 200,
    "method": "POST",
    "startTime": "2022-11-16T12:20:49.083Z"   
  }**

but after filter, I want like:
**"metadata": {
    "orgId": 33274,
    "responseCode": 200,
    "method": "POST",
    "time": "2022-11-16T12:20:49.083Z"   
  }**

tried by below but not working:
**<filter **>
          @type record_transformer
          enable_ruby true
          auto_typecast true
          <record>
            metadata ${{"orgId":record['log_processed']['orgId'], "responseCode":record['log_processed']['responseCode'], "method":record['log_processed']['method'], "time":record['log_processed']['startTime']}}
          </record>
        </filter>**
