### ISSUE TITLE
rewrite tag

### ISSUE THREAD

**Issue by Raboo** [repeatedly/fluent-plugin-record-modifier#42]
Hi

I'm trying to rewrite the tag, but it fail, the original tag remains.

So this is a example workflow.
```
# and add tag with_hostname and source syslog
<filter syslog.**>
  @type record_modifier
  <record>
    source syslog
    original_tag ${tag}
    # syslog source already has hostname
    tag with_hostname
  </record>
</filter>

# add a hostname to all messages that already have a with_source.
<filter with_source>
  @type record_modifier
  <record>
    host "#{Socket.gethostname}"
    tag with_hostname
  </record>
</filter>

<match with_hostname>
```

so **original_tag** is created with the "old" **tag** value. But **tag** doesn't get value `with_hostname`.

Why doesn't this rewrite the **tag**?

**Comment by repeatedly** [comment]
Because you use filter. If you want to change the tag, use output instead.

**Comment by Raboo** [comment]
output? You mean match?

**Comment by Raboo** [comment]
Oh, heck there is even an example in the readme.
https://github.com/repeatedly/fluent-plugin-record-modifier#record_modifier-output

Sorry..
