### ISSUE TITLE
<match **> causes restart

### ISSUE THREAD

**Issue by trombik** [repeatedly/fluent-plugin-record-modifier#5]
i'm not sure  record_modifier is to be blamed, but here is the log.

https://gist.github.com/trombik/1660e21f4868140626a9

if you replace ** with \*.foo or foo.\*, events are processed without problem. tested on ruby 2.0.0 and 2.1.2, the same issue.

rubygem-fluent-mixin-config-placeholders-0.2.4
rubygem-fluent-plugin-record-modifier-0.1.3
rubygem-fluent-plugin-redis-0.2.0
rubygem-fluentd-0.10.48_1
rubygem-http_parser.rb-0.6.0
ruby-2.0.0.353_6,1
rubygem-yajl-ruby-1.2.0
rubygem-sigdump-0.2.2
rubygem-msgpack-0.5.8
rubygem-json-1.8.1
rubygem-cool.io-1.2.4
ruby20-gems-1.8.29

any idea?

**Comment by MikeChou** [comment]
That leads to infinite recursion

**Comment by repeatedly** [comment]
Yes but this is not plugin issue.
You should `foo.filtered` match before `<match **>`.
See following section.

http://docs.fluentd.org/articles/config-file#match-order

From v0.12, using filter avoids this problem.

**Comment by repeatedly** [comment]
record_modifier now has filter version.
