### ISSUE TITLE
Fluentd can't forward logs bacause of: 

### ISSUE THREAD

**Issue by lukasbar** [repeatedly/fluent-plugin-record-modifier#52]
#0 dump an error event: error_class=NoMethodError error="undefined method `has_key?' for nil:NilClass" location="/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-record-modifier-2.0.1/lib/fluent/plugin/filter_record_modifier.rb:173:in `expand'"

**Comment by lukasbar** [comment]
It was problem with configuration, sorry for inconvenience

**Comment by darekg11** [comment]
@lukasbar Could you share what did you change to fix this error? I am having similar problem.
